# Generated by Django 3.2.8 on 2021-10-31 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sao2_std', models.IntegerField()),
                ('heart_rate_mean', models.IntegerField()),
                ('respiratory_rate_mean', models.IntegerField()),
                ('respiratory_rate_std', models.IntegerField()),
                ('heart_rate_alarm_low_max', models.IntegerField()),
                ('sao2_mean', models.IntegerField()),
                ('temperature_mean', models.IntegerField()),
                ('temperature_std', models.IntegerField()),
                ('skin_temperature_std', models.IntegerField()),
                ('skin_temperature_mean', models.IntegerField()),
                ('blood_pressure_std', models.IntegerField()),
                ('blood_pressure_mean', models.IntegerField()),
                ('blood_pressure_systolic_std', models.IntegerField()),
                ('blood_pressure_systolic_mean', models.IntegerField()),
                ('blood_pressure_diastolic_std', models.IntegerField()),
                ('blood_pressure_diastolic_mean', models.IntegerField()),
                ('d10w_amount', models.IntegerField()),
                ('prescription_count', models.IntegerField()),
                ('date_event_count', models.IntegerField()),
                ('white_blood_count', models.IntegerField()),
                ('platelet', models.IntegerField()),
                ('is_recently_traveled', models.BooleanField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('symptom', models.CharField(choices=[('diarrhea', 'diarrhea'), ('cough', 'cough'), ('high_fever', 'high_fever'), ('loss_of_appetite', 'loss_of_appetite')], max_length=30)),
                ('laboratory_type', models.CharField(choices=[('blood', 'blood'), ('stool', 'stool'), ('widal', 'widal')], max_length=30)),
                ('collected_specimen_type', models.CharField(choices=[('blood', 'blood'), ('urine', 'urine')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
