# Generated by Django 3.2.8 on 2021-10-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnose',
            name='blood_pressure_diastolic_mean',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='blood_pressure_diastolic_std',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='blood_pressure_mean',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='blood_pressure_std',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='blood_pressure_systolic_mean',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='blood_pressure_systolic_std',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='heart_rate_alarm_low_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='heart_rate_mean',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='respiratory_rate_mean',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='respiratory_rate_std',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='sao2_mean',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='sao2_std',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='skin_temperature_mean',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='temperature_mean',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
